spring:
  application:
    name: vaga-certa
  datasource:
    url: jdbc:postgresql://localhost:5432/db_vagacerta?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect